apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      nodeSelector: 
        kubernetes.io/arch: "arm64"
      containers:
      - name: my-app
        image: wohligakash/pingpong:sdfsdfdsf
        ports:
        - containerPort: 8080
