name: graviton-test

on:
    push:
        branches:
            - graviton-test

env:
    GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN }}

jobs:

    graviton-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@main

            - name: login to docker hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}  
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set env
              run: echo "GITHUB_BRANCH=$(echo $GITHUB_REF_NAME-$GITHUB_SHA)" >> $GITHUB_ENV

            - name: Helm installation
              run: |                  
                  curl -LO https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz
                  tar -zxvf helm-v3.8.0-linux-amd64.tar.gz
                  mv linux-amd64/helm /usr/local/bin/helm
                  helm version

            - name: Build the Docker image
              run: |
                  docker buildx build -t wohligakash/pingpong:$GITHUB_REF_NAME-$GITHUB_SHA --platform linux/amd64,linux/arm64 --push .
                  docker push wohligakash/pingpong:$GITHUB_REF_NAME-$GITHUB_SHA

            - name: Helm template and git--push
              run: |
                  git clone https://github.com/wohligakash/pingpong-official
                  cd pingpong-official
                  git checkout gitops
                  
                  yq e '.image = "wohligakash/pingpong:${{ env.GITHUB_BRANCH }}"' -i deployment.apps/my-app.yaml
  

                  git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/wohligakash/pingpong-official.git
                  git config user.name "$GITHUB_ACTOR"
                  git config user.email "akash.pawar@wohlig.com"

                  git add .
                  git commit -m "Updating newer image"
                  git push origin gitops

 