name: helm-actions-testing

on:
    push:
        branches:
            - helm
            
    # pull_request:
    #     branches:
    #         - main

# env:
    # GITHUB_TOKEN: ${{ secrets.auth_token }}
    # JIRA_API_TOKEN: ATATT3xFfGF0gHTWM7lhkiEELN_sjoTf1grsm8KuGuzUCVwNf5jjP5pamPwH0my1BXqfB5L8R0gF59QMnf0YP886U8aO_5t3_dHdl2cjnwyPQLZo6OEIWmIsw15ZbsjRlXE3

jobs:
  
    helm-actions-testing:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@main

            - name: login to docker hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}  
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set env
              run: echo "GITHUB_BRANCH=$(echo $GITHUB_REF_NAME-$GITHUB_SHA)" >> $GITHUB_ENV

            - name: Helm installation
              run: |                  
                  curl -LO https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz
                  tar -zxvf helm-v3.8.0-linux-amd64.tar.gz
                  mv linux-amd64/helm /usr/local/bin/helm
                  helm version

            - name: Build the Docker image
              run: |
                  docker build -t wohligakash/pingpong:$GITHUB_REF_NAME-$GITHUB_SHA . 
                  docker push wohligakash/pingpong:$GITHUB_REF_NAME-$GITHUB_SHA

            - name: Helm template and git--push
              run: |
                  git clone https://${{ secrets.USERNAME_GITHUB }}:${{ secrets.TOKEN }}@github.com/Fair-Play-Club/Helm-GitOps-Test.git                
                  cd Helm-GitOps-Test
                  
                  yq e '.tag = "${{ env.GITHUB_BRANCH }}"' -i deployments-values.yaml
                  helm template helm-test ./Helm-GitOps --output-dir ./manifest-file/    

                  git config user.name "wohligakash"
                  git config user.email "akash.pawar@wohlig.com"

                  git add .
                  git commit -m "updating newer image"
                  git push master

    # moving-jira-issue:
    #     runs-on: ubuntu-latest
    #     needs: helm-actions-testing
    #     name: Jira Example
    #     steps:
    #     - uses: atlassian/gajira-login@master
    #       env:
    #         JIRA_BASE_URL: https://playexch.atlassian.net
    #         JIRA_USER_EMAIL: akash.pawar@wohlig.com
    #         JIRA_API_TOKEN: ${JIRA_API_TOKEN}
        # - uses: tuanddd/jira-automate-transition@v1.0.5
        #   with:
        #     github-token: ${{ secrets.GITHUB_TOKEN }}
        #     column-to-move-to-when-review-requested: Done
        #     column-to-move-to-when-changes-requested: Done
        #     column-to-move-to-when-merged: Done              # above
        #     jira-issue-id: D-1240