name: Build-Commit-Push-Jira-Transition

on:
    push:
        branches:
            - uat

env:
    GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN }}

jobs:

    Build-Commit-Push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@main

            - name: login to docker hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}  
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set env
              run: echo "GITHUB_BRANCH=$(echo $GITHUB_REF_NAME-$GITHUB_SHA)" >> $GITHUB_ENV

            - name: Helm installation
              run: |                  
                  curl -LO https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz
                  tar -zxvf helm-v3.8.0-linux-amd64.tar.gz
                  mv linux-amd64/helm /usr/local/bin/helm
                  helm version

            - name: Build the Docker image
              run: |
                  docker build -t wohligakash/pingpong:$GITHUB_REF_NAME-$GITHUB_SHA . 
                  docker push wohligakash/pingpong:$GITHUB_REF_NAME-$GITHUB_SHA

            - name: Helm template and git--push
              run: |
                  git clone https://github.com/wohligakash/pingpong-official-gitops.git
                  cd pingpong-official-gitops
                  
                  yq e '.image = "wohligakash/pingpong:${{ env.GITHUB_BRANCH }}"' -i helm-chart/values.yaml
                  helm template uat-env ./helm-chart > manifest-file/manifests.yaml
                  cat manifest-file/manifests.yaml    

                  git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/wohligakash/pingpong-official-gitops.git
                  git config user.name "$GITHUB_ACTOR"
                  git config user.email "akash.pawar@wohlig.com"

                  git add .
                  git commit -m "Updating newer image"
                  git push origin main

    Jira-ticket-transition:
        runs-on: ubuntu-latest
        needs: helm-actions-testing
        steps:

            - name: Jira Login
              uses: atlassian/gajira-login@master
              env:
                JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
                JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
                JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
                
            - name: Find
              id: issue-key
              uses: atlassian/gajira-find-issue-key@v3
              with:
                string: ${{ github.ref }}

            - name: Transition issue
              uses: atlassian/gajira-transition@v3
              with:
                issue: ${{ steps.issue-key.outputs.issue }}
                transition: "In Progress"